export const AUDIO_ACCENT_FREQUENCY_HZ = 1600;
export const AUDIO_REGULAR_FREQUENCY_HZ = 800;
export const AUDIO_ACCENT_DURATION_SEC = 0.12;
export const AUDIO_REGULAR_DURATION_SEC = 0.06;
export const AUDIO_RAMP_MIN_GAIN = 0.001;

export const SCHEDULER_LOOKAHEAD_SEC = 0.1;
export const DEFAULT_START_DELAY_SEC = 0.05;
export const MS_PER_SECOND = 1000;
export const SECONDS_PER_MINUTE = 60;
